apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-deployment
spec:
  selector:
    matchLabels:
      app: guest-pod
  replicas: 2
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: guest-pod
    spec:
      containers:
      - name: guest-container
        image: academyitwill/guest:v1
        imagePullPolicy: Always
        env:
          - name: USER_PROFILE
            value: remote-oracle 
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: guest-service
spec:
  selector:
   app: guest-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
