apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: {mysql-root-password}
  mysql-user-id: {mysql-user-id}
  mysql-user-password: {mysql-user-password}
  mysql-database-name: {mysql-database-name}
