apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  #mysql-root-password: root
  #mysql-user-id: jdeveloper
  #mysql-user-password: jdeveloper
  #mysql-database-name: guestdb
  #https://www.base64encode.net/
  mysql-root-password: cm9vdA==
  mysql-user-id: amRldmVsb3Blcg==
  mysql-user-password: amRldmVsb3Blcg==
  mysql-database-name: Z3Vlc3RkYg==
