apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: root
  mysql-user-id: jdeveloper
  mysql-user-password: jdeveloper
  mysql-database-name: guestdb
